'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Brain, Printer } from 'lucide-react';
import type { Card } from '@/lib/types';

function parseBack(back: string): { answer: string; explanation?: string; keyFormula?: string; examTip?: string; mnemonic?: string } {
  try {
    const p = JSON.parse(back);
    if (p && p.answer) return p;
  } catch { /* plain text */ }
  return { answer: back };
}

interface DeckData {
  id: string;
  title: string;
  description?: string;
  source_filename?: string;
  cards: Card[];
}

export default function PrintPage() {
  const { id } = useParams<{ id: string }>();
  const [deck, setDeck] = useState<DeckData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/decks/${id}`)
      .then((r) => r.json())
      .then((data) => { setDeck(data); setLoading(false); });
  }, [id]);

  // Auto-open print dialog after content loads
  useEffect(() => {
    if (!loading && deck) {
      const t = setTimeout(() => window.print(), 600);
      return () => clearTimeout(t);
    }
  }, [loading, deck]);

  if (loading || !deck) {
    return (
      <div className="min-h-screen flex items-center justify-center font-sans text-gray-500">
        Preparing flashcards…
      </div>
    );
  }

  const cards = deck.cards ?? [];

  return (
    <>
      {/* Screen-only controls */}
      <div className="print:hidden fixed top-0 inset-x-0 z-50 bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between shadow-sm">
        <div className="flex items-center gap-2">
          <Brain size={18} className="text-primary" />
          <span className="font-serif text-gray-900 text-lg">{deck.title}</span>
          <span className="text-sm text-gray-400 font-sans ml-2">· {cards.length} cards</span>
        </div>
        <button
          onClick={() => window.print()}
          className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#2C1810] hover:bg-[#4A2C20] text-white text-sm font-medium font-sans transition-colors"
        >
          <Printer size={15} />
          Print / Save as PDF
        </button>
      </div>

      {/* Print body */}
      <div className="pt-16 print:pt-0 px-6 pb-8 print:px-0 print:pb-0 bg-white min-h-screen">

        {/* Cover page */}
        <div className="print:h-screen flex flex-col items-center justify-center text-center mb-16 print:mb-0 print:break-after-page">
          <div className="w-16 h-16 rounded-2xl bg-[#2C1810] flex items-center justify-center mx-auto mb-6">
            <Brain size={30} className="text-white" />
          </div>
          <h1 className="text-4xl font-serif text-gray-900 mb-3">{deck.title}</h1>
          {deck.description && (
            <p className="text-gray-500 font-sans text-base max-w-md mb-4">{deck.description}</p>
          )}
          {deck.source_filename && (
            <p className="text-xs text-gray-400 font-sans">Source: {deck.source_filename}</p>
          )}
          <p className="mt-6 text-sm text-gray-400 font-sans">{cards.length} flashcards · Generated by CramCraft</p>
          <p className="mt-1 text-xs text-gray-300 font-sans">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>

        {/* Flashcard grid — 2 per row, each card shows Q + A */}
        <div className="grid grid-cols-1 sm:grid-cols-2 print:grid-cols-2 gap-6 print:gap-0 print:p-4 max-w-4xl mx-auto print:max-w-none">
          {cards.map((card, idx) => {
            const rich = parseBack(card.back);
            return (
              <div
                key={card.id}
                className="border-2 border-gray-200 rounded-2xl print:rounded-none print:border print:border-gray-300 overflow-hidden print:break-inside-avoid"
                style={{ pageBreakInside: 'avoid' }}
              >
                {/* Card number + type */}
                <div className="flex items-center justify-between px-4 py-2 bg-gray-50 print:bg-gray-100 border-b border-gray-200">
                  <span className="text-xs font-sans font-semibold text-primary uppercase tracking-wide">
                    Card {idx + 1}
                  </span>
                  <span className="text-xs font-sans text-gray-400 capitalize">
                    {card.card_type?.replace(/_/g, ' ')}
                  </span>
                </div>

                {/* Question */}
                <div className="px-4 py-3 border-b border-dashed border-gray-200">
                  <p className="text-[10px] font-sans font-semibold text-gray-400 uppercase tracking-wider mb-1">Question</p>
                  <p className="font-serif text-gray-900 text-sm leading-snug">{card.front}</p>
                </div>

                {/* Answer */}
                <div className="px-4 py-3 bg-amber-50 print:bg-amber-50">
                  <p className="text-[10px] font-sans font-semibold text-primary-700 uppercase tracking-wider mb-1">Answer</p>
                  <p className="font-sans text-gray-800 text-sm leading-snug mb-2">{rich.answer}</p>

                  {rich.keyFormula && (
                    <p className="text-xs font-mono text-[#2C1810] bg-amber-100 rounded px-2 py-1 mb-1">
                      📐 {rich.keyFormula}
                    </p>
                  )}
                  {rich.explanation && (
                    <p className="text-xs text-gray-600 leading-snug mb-1">
                      <span className="font-semibold">Note: </span>{rich.explanation}
                    </p>
                  )}
                  {rich.mnemonic && (
                    <p className="text-xs text-purple-700 italic leading-snug mb-1">
                      🧠 {rich.mnemonic}
                    </p>
                  )}
                  {rich.examTip && (
                    <p className="text-xs text-amber-700 leading-snug">
                      💡 Tip: {rich.examTip}
                    </p>
                  )}
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="hidden print:block text-center text-xs text-gray-300 font-sans py-4">
          {deck.title} · CramCraft · {cards.length} cards
        </div>
      </div>
    </>
  );
}
