-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. DECKS TABLE
CREATE TABLE IF NOT EXISTS decks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id TEXT NOT NULL DEFAULT 'local',
  title TEXT NOT NULL,
  description TEXT,
  source_filename TEXT,
  card_count INTEGER DEFAULT 0,
  mastery_percentage REAL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_studied_at TIMESTAMPTZ
);

-- 2. CARDS TABLE (SM-2 Spaced Repetition)
CREATE TABLE IF NOT EXISTS cards (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  deck_id UUID NOT NULL,
  front TEXT NOT NULL,
  back TEXT NOT NULL,
  card_type TEXT DEFAULT 'concept',
  difficulty INTEGER DEFAULT 0,
  repetitions INTEGER DEFAULT 0,
  easiness_factor REAL DEFAULT 2.5,
  interval_days INTEGER DEFAULT 0,
  next_review_at TIMESTAMPTZ DEFAULT NOW(),
  last_reviewed_at TIMESTAMPTZ,
  CONSTRAINT fk_deck FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE
);

-- 3. STUDY STATS TABLE (Fixed the AUTOINCREMENT error)
CREATE TABLE IF NOT EXISTS study_stats (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id TEXT NOT NULL DEFAULT 'local',
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  cards_studied INTEGER DEFAULT 0,
  decks_studied JSONB DEFAULT '[]'::jsonb, -- Using JSONB for better performance in Postgres
  UNIQUE(user_id, date)
);

-- 4. EXAM SESSIONS TABLE
CREATE TABLE IF NOT EXISTS exam_sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id TEXT NOT NULL DEFAULT 'local',
  title TEXT NOT NULL,
  source_filename TEXT,
  summary TEXT,
  question_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. EXAM QUESTIONS TABLE
CREATE TABLE IF NOT EXISTS exam_questions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id UUID NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  importance TEXT DEFAULT 'important',
  question_type TEXT DEFAULT 'conceptual',
  topic TEXT,
  order_index INTEGER DEFAULT 0,
  CONSTRAINT fk_session FOREIGN KEY (session_id) REFERENCES exam_sessions(id) ON DELETE CASCADE
);

-- 6. NOTE CARDS TABLE
CREATE TABLE IF NOT EXISTS note_cards (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  deck_id UUID NOT NULL,
  title TEXT NOT NULL,
  key_points TEXT NOT NULL,
  example TEXT,
  category TEXT DEFAULT 'overview',
  order_index INTEGER DEFAULT 0,
  CONSTRAINT fk_note_deck FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE
);

-- 7. REVISION SHEETS TABLE
CREATE TABLE IF NOT EXISTS revision_sheets (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  deck_id UUID NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  sections TEXT NOT NULL,
  one_line_answer TEXT,
  mnemonics JSONB DEFAULT '[]'::jsonb,
  order_index INTEGER DEFAULT 0,
  CONSTRAINT fk_rev_deck FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_cards_deck_id ON cards(deck_id);
CREATE INDEX IF NOT EXISTS idx_cards_next_review ON cards(next_review_at);
CREATE INDEX IF NOT EXISTS idx_study_stats_date ON study_stats(date);
CREATE INDEX IF NOT EXISTS idx_exam_questions_session ON exam_questions(session_id);
CREATE INDEX IF NOT EXISTS idx_note_cards_deck ON note_cards(deck_id);
CREATE INDEX IF NOT EXISTS idx_revision_sheets_deck ON revision_sheets(deck_id);