import { NextRequest, NextResponse } from 'next/server';
import { getDeckById, getCardsByDeckId } from '@/lib/db';
import { getAuthUserId } from '@/lib/auth';
import type { Card, Deck } from '@/lib/types';

type DeckRow = Deck & { user_id: string };

function parseBack(back: string): { answer: string; explanation?: string; keyFormula?: string; examTip?: string; mnemonic?: string } {
  try {
    const p = JSON.parse(back);
    if (p && p.answer) return p;
  } catch { /* plain text */ }
  return { answer: back };
}

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const userId = await getAuthUserId();
    if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const deck = getDeckById(params.id) as DeckRow | undefined;
    if (!deck) return NextResponse.json({ error: 'Deck not found' }, { status: 404 });
    if (deck.user_id !== userId) return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

    const cards = getCardsByDeckId(params.id) as Card[];
    const safeTitle = deck.title.replace(/[^a-z0-9\s-]/gi, '').trim().replace(/\s+/g, '_');
    const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    // Build a clean plain-text study document
    const lines: string[] = [
      '═'.repeat(60),
      `  ${deck.title.toUpperCase()}`,
      '═'.repeat(60),
      deck.description ? `  ${deck.description}` : '',
      `  ${cards.length} flashcards  ·  Generated by CramCraft  ·  ${now}`,
      '',
    ].filter((l) => l !== undefined);

    cards.forEach((card, i) => {
      const rich = parseBack(card.back);
      lines.push('─'.repeat(60));
      lines.push(`Card ${i + 1} of ${cards.length}  [${(card.card_type ?? 'concept').replace(/_/g, ' ').toUpperCase()}]`);
      lines.push('');
      lines.push(`  Q: ${card.front}`);
      lines.push('');
      lines.push(`  A: ${rich.answer}`);
      if (rich.keyFormula) lines.push(`     Formula: ${rich.keyFormula}`);
      if (rich.explanation) lines.push(`     Note:    ${rich.explanation}`);
      if (rich.mnemonic)   lines.push(`     Memory:  ${rich.mnemonic}`);
      if (rich.examTip)    lines.push(`     Tip:     ${rich.examTip}`);
      lines.push('');
    });

    lines.push('═'.repeat(60));
    lines.push(`End of deck — ${deck.title}`);
    lines.push('═'.repeat(60));

    const text = lines.join('\n');

    return new NextResponse(text, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${safeTitle}_flashcards.txt"`,
      },
    });
  } catch (error) {
    console.error('[GET /api/decks/[id]/export]', error);
    return NextResponse.json({ error: 'Failed to export deck' }, { status: 500 });
  }
}
